//! Unified humanoid bone names across VRM 0.0 and VRM 1.0.

use vrm_spec::vrm_0_0;
use vrm_spec::vrmc_vrm_1_0::HumanBoneName;

/// A humanoid bone present in either VRM 0.0 or VRM 1.0 specifications.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BoneName {
    Hips,
    Spine,
    Chest,
    UpperChest,
    Neck,
    Head,
    Jaw,
    LeftEye,
    RightEye,
    LeftShoulder,
    LeftUpperArm,
    LeftLowerArm,
    LeftHand,
    LeftThumbMetacarpal,
    LeftThumbProximal,
    LeftThumbIntermediate,
    LeftThumbDistal,
    LeftIndexProximal,
    LeftIndexIntermediate,
    LeftIndexDistal,
    LeftMiddleProximal,
    LeftMiddleIntermediate,
    LeftMiddleDistal,
    LeftRingProximal,
    LeftRingIntermediate,
    LeftRingDistal,
    LeftLittleProximal,
    LeftLittleIntermediate,
    LeftLittleDistal,
    RightShoulder,
    RightUpperArm,
    RightLowerArm,
    RightHand,
    RightThumbMetacarpal,
    RightThumbProximal,
    RightThumbIntermediate,
    RightThumbDistal,
    RightIndexProximal,
    RightIndexIntermediate,
    RightIndexDistal,
    RightMiddleProximal,
    RightMiddleIntermediate,
    RightMiddleDistal,
    RightRingProximal,
    RightRingIntermediate,
    RightRingDistal,
    RightLittleProximal,
    RightLittleIntermediate,
    RightLittleDistal,
    LeftUpperLeg,
    LeftLowerLeg,
    LeftFoot,
    LeftToes,
    RightUpperLeg,
    RightLowerLeg,
    RightFoot,
    RightToes,
}

impl BoneName {
    /// Canonical bone name, used for debug output and `Display`.
    pub fn name(&self) -> &'static str {
        use BoneName::*;
        match self {
            Hips => "hips",
            Spine => "spine",
            Chest => "chest",
            UpperChest => "upperChest",
            Neck => "neck",
            Head => "head",
            Jaw => "jaw",
            LeftEye => "leftEye",
            RightEye => "rightEye",
            LeftShoulder => "leftShoulder",
            LeftUpperArm => "leftUpperArm",
            LeftLowerArm => "leftLowerArm",
            LeftHand => "leftHand",
            LeftThumbMetacarpal => "leftThumbMetacarpal",
            LeftThumbProximal => "leftThumbProximal",
            LeftThumbIntermediate => "leftThumbIntermediate",
            LeftThumbDistal => "leftThumbDistal",
            LeftIndexProximal => "leftIndexProximal",
            LeftIndexIntermediate => "leftIndexIntermediate",
            LeftIndexDistal => "leftIndexDistal",
            LeftMiddleProximal => "leftMiddleProximal",
            LeftMiddleIntermediate => "leftMiddleIntermediate",
            LeftMiddleDistal => "leftMiddleDistal",
            LeftRingProximal => "leftRingProximal",
            LeftRingIntermediate => "leftRingIntermediate",
            LeftRingDistal => "leftRingDistal",
            LeftLittleProximal => "leftLittleProximal",
            LeftLittleIntermediate => "leftLittleIntermediate",
            LeftLittleDistal => "leftLittleDistal",
            RightShoulder => "rightShoulder",
            RightUpperArm => "rightUpperArm",
            RightLowerArm => "rightLowerArm",
            RightHand => "rightHand",
            RightThumbMetacarpal => "rightThumbMetacarpal",
            RightThumbProximal => "rightThumbProximal",
            RightThumbIntermediate => "rightThumbIntermediate",
            RightThumbDistal => "rightThumbDistal",
            RightIndexProximal => "rightIndexProximal",
            RightIndexIntermediate => "rightIndexIntermediate",
            RightIndexDistal => "rightIndexDistal",
            RightMiddleProximal => "rightMiddleProximal",
            RightMiddleIntermediate => "rightMiddleIntermediate",
            RightMiddleDistal => "rightMiddleDistal",
            RightRingProximal => "rightRingProximal",
            RightRingIntermediate => "rightRingIntermediate",
            RightRingDistal => "rightRingDistal",
            RightLittleProximal => "rightLittleProximal",
            RightLittleIntermediate => "rightLittleIntermediate",
            RightLittleDistal => "rightLittleDistal",
            LeftUpperLeg => "leftUpperLeg",
            LeftLowerLeg => "leftLowerLeg",
            LeftFoot => "leftFoot",
            LeftToes => "leftToes",
            RightUpperLeg => "rightUpperLeg",
            RightLowerLeg => "rightLowerLeg",
            RightFoot => "rightFoot",
            RightToes => "rightToes",
        }
    }

    /// Convert a VRM 1.0 bone name.
    pub fn from_vrm1(name: HumanBoneName) -> Self {
        use BoneName::*;
        use HumanBoneName as H;
        match name {
            H::Hips => Hips,
            H::Spine => Spine,
            H::Chest => Chest,
            H::UpperChest => UpperChest,
            H::Neck => Neck,
            H::Head => Head,
            H::Jaw => Jaw,
            H::LeftEye => LeftEye,
            H::RightEye => RightEye,
            H::LeftShoulder => LeftShoulder,
            H::LeftUpperArm => LeftUpperArm,
            H::LeftLowerArm => LeftLowerArm,
            H::LeftHand => LeftHand,
            H::LeftThumbMetacarpal => LeftThumbMetacarpal,
            H::LeftThumbProximal => LeftThumbProximal,
            H::LeftThumbDistal => LeftThumbDistal,
            H::LeftIndexProximal => LeftIndexProximal,
            H::LeftIndexIntermediate => LeftIndexIntermediate,
            H::LeftIndexDistal => LeftIndexDistal,
            H::LeftMiddleProximal => LeftMiddleProximal,
            H::LeftMiddleIntermediate => LeftMiddleIntermediate,
            H::LeftMiddleDistal => LeftMiddleDistal,
            H::LeftRingProximal => LeftRingProximal,
            H::LeftRingIntermediate => LeftRingIntermediate,
            H::LeftRingDistal => LeftRingDistal,
            H::LeftLittleProximal => LeftLittleProximal,
            H::LeftLittleIntermediate => LeftLittleIntermediate,
            H::LeftLittleDistal => LeftLittleDistal,
            H::RightShoulder => RightShoulder,
            H::RightUpperArm => RightUpperArm,
            H::RightLowerArm => RightLowerArm,
            H::RightHand => RightHand,
            H::RightThumbMetacarpal => RightThumbMetacarpal,
            H::RightThumbProximal => RightThumbProximal,
            H::RightThumbDistal => RightThumbDistal,
            H::RightIndexProximal => RightIndexProximal,
            H::RightIndexIntermediate => RightIndexIntermediate,
            H::RightIndexDistal => RightIndexDistal,
            H::RightMiddleProximal => RightMiddleProximal,
            H::RightMiddleIntermediate => RightMiddleIntermediate,
            H::RightMiddleDistal => RightMiddleDistal,
            H::RightRingProximal => RightRingProximal,
            H::RightRingIntermediate => RightRingIntermediate,
            H::RightRingDistal => RightRingDistal,
            H::RightLittleProximal => RightLittleProximal,
            H::RightLittleIntermediate => RightLittleIntermediate,
            H::RightLittleDistal => RightLittleDistal,
            H::LeftUpperLeg => LeftUpperLeg,
            H::LeftLowerLeg => LeftLowerLeg,
            H::LeftFoot => LeftFoot,
            H::LeftToes => LeftToes,
            H::RightUpperLeg => RightUpperLeg,
            H::RightLowerLeg => RightLowerLeg,
            H::RightFoot => RightFoot,
            H::RightToes => RightToes,
        }
    }

    /// Convert a VRM 0.0 bone name. VRM 0.0 has no metacarpal bones.
    pub fn from_vrm0(name: vrm_0_0::Bone) -> Option<Self> {
        use BoneName as B;
        use vrm_0_0::Bone as O;
        Some(match name {
            O::Hips => B::Hips,
            O::Spine => B::Spine,
            O::Chest => B::Chest,
            O::UpperChest => B::UpperChest,
            O::Neck => B::Neck,
            O::Head => B::Head,
            O::Jaw => B::Jaw,
            O::LeftEye => B::LeftEye,
            O::RightEye => B::RightEye,
            O::LeftShoulder => B::LeftShoulder,
            O::LeftUpperArm => B::LeftUpperArm,
            O::LeftLowerArm => B::LeftLowerArm,
            O::LeftHand => B::LeftHand,
            O::LeftThumbProximal => B::LeftThumbProximal,
            O::LeftThumbIntermediate => B::LeftThumbIntermediate,
            O::LeftThumbDistal => B::LeftThumbDistal,
            O::LeftIndexProximal => B::LeftIndexProximal,
            O::LeftIndexIntermediate => B::LeftIndexIntermediate,
            O::LeftIndexDistal => B::LeftIndexDistal,
            O::LeftMiddleProximal => B::LeftMiddleProximal,
            O::LeftMiddleIntermediate => B::LeftMiddleIntermediate,
            O::LeftMiddleDistal => B::LeftMiddleDistal,
            O::LeftRingProximal => B::LeftRingProximal,
            O::LeftRingIntermediate => B::LeftRingIntermediate,
            O::LeftRingDistal => B::LeftRingDistal,
            O::LeftLittleProximal => B::LeftLittleProximal,
            O::LeftLittleIntermediate => B::LeftLittleIntermediate,
            O::LeftLittleDistal => B::LeftLittleDistal,
            O::RightShoulder => B::RightShoulder,
            O::RightUpperArm => B::RightUpperArm,
            O::RightLowerArm => B::RightLowerArm,
            O::RightHand => B::RightHand,
            O::RightThumbProximal => B::RightThumbProximal,
            O::RightThumbIntermediate => B::RightThumbIntermediate,
            O::RightThumbDistal => B::RightThumbDistal,
            O::RightIndexProximal => B::RightIndexProximal,
            O::RightIndexIntermediate => B::RightIndexIntermediate,
            O::RightIndexDistal => B::RightIndexDistal,
            O::RightMiddleProximal => B::RightMiddleProximal,
            O::RightMiddleIntermediate => B::RightMiddleIntermediate,
            O::RightMiddleDistal => B::RightMiddleDistal,
            O::RightRingProximal => B::RightRingProximal,
            O::RightRingIntermediate => B::RightRingIntermediate,
            O::RightRingDistal => B::RightRingDistal,
            O::RightLittleProximal => B::RightLittleProximal,
            O::RightLittleIntermediate => B::RightLittleIntermediate,
            O::RightLittleDistal => B::RightLittleDistal,
            O::LeftUpperLeg => B::LeftUpperLeg,
            O::LeftLowerLeg => B::LeftLowerLeg,
            O::LeftFoot => B::LeftFoot,
            O::LeftToes => B::LeftToes,
            O::RightUpperLeg => B::RightUpperLeg,
            O::RightLowerLeg => B::RightLowerLeg,
            O::RightFoot => B::RightFoot,
            O::RightToes => B::RightToes,
        })
    }
}

impl std::fmt::Display for BoneName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}
